---
language: ruby
script:
    - 'cd test/dummy && rake db:migrate db:test:prepare'
    - rake test
rvm:
  - '1.9.3'
  - '2.0.0'

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
