---
language: ruby
script:
    - 'cd test/dummy && rake db:migrate db:test:prepare'
    - rake test
rvm:
  - '1.9.3'
  - '2.0.0'

gemfile:
  - gemfiles/Gemfile.default
  - gemfiles/Gemfile.rails32

env:
  - DB=sqlite
  # - DB=mysql
  # - DB=postgresql

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails32
      env: DB=sqlite

before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
  - rake dummy:setup
  - rake app:db:migrate
  - rake app:db:migrate RAILS_ENV=test
